version: '3.4'

services:
  student.identityserver:
    image: ${DOCKER_REGISTRY-}studentidentityserver
    build:
      context: .
      dockerfile: Student.IdentityServer/Dockerfile
    ports:
    - "443:443"
    - "80:80"
    - "50000:50000"
    container_name: identity
    networks:
      - postgres
   
  postgres:
    container_name: postgres
    image: postgres:alpine3.14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
       - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.1
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
